export const LOCALSTORAGE_KEY_DISCARDED_DB = 'PPTIST_DISCARDED_DB'
export const LOCALSTORAGE_KEY_SLIDES = 'PPTIST_SLIDES'
export const LOCALSTORAGE_KEY_TITLE = 'PPTIST_TITLE'
export const LOCALSTORAGE_KEY_THEME = 'PPTIST_THEME'